"""Abstract LLM provider interface and shared data structures."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol


class LLMProvider(Protocol):
    """Protocol defining the interface that all LLM providers must implement."""

    async def analyze_image(
        self,
        image_path: str,
        prompt: str,
        system: str = "",
        response_schema: dict | None = None,
    ) -> dict:
        """Send an image together with a text prompt and receive a structured response.

        Args:
            image_path: Filesystem path to the image file.
            prompt: The user prompt describing what analysis to perform.
            system: Optional system prompt to set context / persona.
            response_schema: Optional JSON-schema dict; when provided the
                implementation should attempt to parse the model output as JSON
                conforming to this schema.

        Returns:
            A dict with at least the keys: content, parsed, model,
            input_tokens, output_tokens.
        """
        ...

    async def analyze_text(
        self,
        text: str,
        prompt: str,
        system: str = "",
        response_schema: dict | None = None,
    ) -> dict:
        """Send a text payload together with a prompt and receive a structured response.

        Args:
            text: The text content to analyze.
            prompt: The user prompt describing what analysis to perform.
            system: Optional system prompt to set context / persona.
            response_schema: Optional JSON-schema dict; when provided the
                implementation should attempt to parse the model output as JSON
                conforming to this schema.

        Returns:
            A dict with at least the keys: content, parsed, model,
            input_tokens, output_tokens.
        """
        ...

    async def analyze_images_batch(
        self,
        requests: list[dict],
    ) -> list[dict]:
        """Batch image analysis for throughput and cost savings.

        Args:
            requests: A list of request dicts, each containing at minimum
                ``image_path`` and ``prompt``, with optional ``system``,
                ``model``, and ``response_schema`` keys.

        Returns:
            A list of response dicts in the same order as *requests*, each
            containing: content, parsed, model, input_tokens, output_tokens.
        """
        ...


@dataclass
class LLMResponse:
    """Structured container for an LLM provider response.

    Attributes:
        content: The raw text content returned by the model.
        parsed: The parsed JSON object if the response was successfully
            parsed, otherwise ``None``.
        model: The model identifier that produced this response.
        input_tokens: Number of input tokens consumed by the request.
        output_tokens: Number of output tokens generated by the model.
    """

    content: str
    parsed: dict | None
    model: str
    input_tokens: int
    output_tokens: int
